import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";


import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Puedes agregar más pesos si quieres
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <div className="bg-white">

        <div >
          <Navbar />
        </div>
        </div>
        {children}
      </body>
    </html>
  );
}
